# Generated by Django 5.2 on 2025-04-14 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desp', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('no_of_sales', models.IntegerField()),
            ],
        ),
    ]
