# Generated by Django 5.2 on 2025-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
