# Generated by Django 5.2 on 2025-04-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
