# Generated by Django 5.2 on 2025-04-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
