# Generated by Django 5.2 on 2025-04-19 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='temp_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
