# Generated by Django 5.2 on 2025-04-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_temp_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_models_id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='id',
            new_name='address_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='temp_uuid',
        ),
    ]
